 
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConection.ConexaoBD;
import modeloDao.DaoContas;
import modeloBeans.BeansContas;
import modeloBeans.ModeloTabelaContas;

/**
 *
 * @author Pedro
 */
public class CasaCadastro extends javax.swing.JFrame {

    BeansContas mode=new BeansContas();
    DaoContas control=new DaoContas();
    ConexaoBD conex=new ConexaoBD();
    int flag=0;
    
    
    public CasaCadastro() {
        initComponents();
        
        preencherTabela("select * from contas order by nome_morador");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldContasPagas = new javax.swing.JTextField();
        jTextFieldContaApagar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMorador = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisas = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jTextFieldNomeMoradorCont = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNumeroCasa1 = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextCodigo = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("Cadastro De Contas:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 190, 40);

        jLabel2.setText("Contas A Pagar:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 210, 140, 46);

        jLabel3.setText("Contas Pagas:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 270, 113, 37);

        jLabel4.setText("Numero Da Casa:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 170, 113, 34);

        jTextFieldContasPagas.setEnabled(false);
        getContentPane().add(jTextFieldContasPagas);
        jTextFieldContasPagas.setBounds(190, 280, 113, 30);

        jTextFieldContaApagar.setEnabled(false);
        jTextFieldContaApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContaApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldContaApagar);
        jTextFieldContaApagar.setBounds(190, 220, 113, 30);

        jTableMorador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMoradorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMorador);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(441, 100, 452, 346);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(428, 58, 154, 0);

        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(441, 63, 228, 30);

        jButtonPesquisas.setText("Pesquisar:");
        jButtonPesquisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisas);
        jButtonPesquisas.setBounds(676, 65, 100, 25);

        jButtonNovo.setText("Novo:");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(20, 400, 90, 25);

        jButtonEditar.setText("Editar:");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(20, 440, 87, 25);

        jButtonSalvar.setText("Salvar:");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(130, 440, 87, 25);

        jButtonLimpar.setText("Limpar:");
        jButtonLimpar.setEnabled(false);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(240, 400, 77, 25);

        jTextFieldNomeMoradorCont.setEnabled(false);
        jTextFieldNomeMoradorCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeMoradorContActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeMoradorCont);
        jTextFieldNomeMoradorCont.setBounds(190, 120, 110, 30);

        jLabel6.setText("Nome Do Morador:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 120, 110, 30);

        jTextFieldNumeroCasa1.setEnabled(false);
        jTextFieldNumeroCasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroCasa1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNumeroCasa1);
        jTextFieldNumeroCasa1.setBounds(190, 170, 110, 30);

        jButtonCancelar.setText("Cancelar:");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(130, 400, 90, 25);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 50, 880, 2);

        jLabel8.setText("ID:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 60, 41, 16);

        jTextCodigo.setEnabled(false);
        jTextCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCodigo);
        jTextCodigo.setBounds(50, 60, 90, 22);

        jButtonExcluir.setText("Excluir:");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(240, 440, 75, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo de imagem.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -4, 910, 490);

        setSize(new java.awt.Dimension(923, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldContaApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContaApagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContaApagarActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldNomeMoradorContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeMoradorContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeMoradorContActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
    
       if(flag==1){ 
        
        mode.setNome(jTextFieldNomeMoradorCont.getText());
        mode.setNumeroCasa(jTextFieldNumeroCasa1.getText());
        mode.setContasApagar(jTextFieldContaApagar.getText());
        mode.setContasPagas(jTextFieldContasPagas.getText());
        
        
        
        control.salvar1(mode);
        
        
        jTextFieldContaApagar.setText("");
        jTextFieldNumeroCasa1.setText("");
        jTextFieldContasPagas.setText("");
        jTextFieldNomeMoradorCont.setText("");
        
        jTextFieldNomeMoradorCont.setEnabled(false);
        jTextFieldNumeroCasa1.setEnabled(false);
        jTextFieldContaApagar.setEnabled(false);
        jTextFieldContasPagas.setEnabled(false);
        
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        preencherTabela("select * from contas order by nome_morador");
       
       }else{
       //editar contas
       mode.setCodigo(Integer.parseInt(jTextCodigo.getText()));
       mode.setNome(jTextFieldNomeMoradorCont.getText());
       mode.setNumeroCasa(jTextFieldNumeroCasa1.getText());
       mode.setContasApagar(jTextFieldContaApagar.getText());
       mode.setContasPagas(jTextFieldContasPagas.getText());
       
       control.Editar(mode);
       
       jTextFieldNomeMoradorCont.setEnabled(false);
        jTextFieldNumeroCasa1.setEnabled(false);
        jTextFieldContaApagar.setEnabled(false);
        jTextFieldContasPagas.setEnabled(false);
        
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jButtonSalvar.setEnabled(false);
       
        preencherTabela("select * from contas order by nome_morador");
       
       }
       
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
        
        jTextFieldContaApagar.setText("");
        jTextFieldNumeroCasa1.setText("");
        jTextFieldContasPagas.setText("");
        jTextFieldNomeMoradorCont.setText("");
        
        jTextFieldNomeMoradorCont.setEnabled(true);
        jTextFieldNumeroCasa1.setEnabled(true);
        jTextFieldContaApagar.setEnabled(true);
        jTextFieldContasPagas.setEnabled(true);
        
        
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonLimpar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisasActionPerformed

        mode.setPesquisar(jTextFieldPesquisar.getText());
        
        BeansContas model=control.buscarContas(mode);
        jTextCodigo.setText(String.valueOf(model.getCodigo()));
        jTextFieldNomeMoradorCont.setText(model.getNome());
        jTextFieldNumeroCasa1.setText(model.getNumeroCasa());
        
        jTextFieldContaApagar.setText(model.getContasApagar());
        jTextFieldContasPagas.setText(model.getContasPagas());
        
        
        jButtonEditar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonPesquisasActionPerformed

    private void jTextFieldNumeroCasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroCasa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroCasa1ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
        flag=2;
        
        jTextFieldNomeMoradorCont.setEnabled(true);
        jTextFieldNumeroCasa1.setEnabled(true);
        jTextFieldContaApagar.setEnabled(true);
        jTextFieldContasPagas.setEnabled(true);
        
        
        
        jButtonSalvar.setEnabled(true);
        jButtonLimpar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed

        flag=1;
        jTextFieldNomeMoradorCont.setEnabled(true);
        jTextFieldNumeroCasa1.setEnabled(true);
        jTextFieldContaApagar.setEnabled(true);
        jTextFieldContasPagas.setEnabled(true);
        
        
        
        
        jButtonSalvar.setEnabled(true);
        jButtonLimpar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        jTextCodigo.setText("");
         jTextFieldContaApagar.setText("");
        jTextFieldNumeroCasa1.setText("");
        jTextFieldContasPagas.setText("");
        jTextFieldNomeMoradorCont.setText("");
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        jTextFieldNomeMoradorCont.setEnabled(!true);
        jTextFieldNumeroCasa1.setEnabled(!true);
        jTextFieldContaApagar.setEnabled(!true);
        jTextFieldContasPagas.setEnabled(!true);
        
        
        
        jTextFieldContaApagar.setText("");
        jTextFieldNumeroCasa1.setText("");
        jTextFieldContasPagas.setText("");
        jTextFieldNomeMoradorCont.setText("");
        
        jButtonNovo.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodigoActionPerformed
        
    }//GEN-LAST:event_jTextCodigoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       
        int resposta=0;
        resposta=JOptionPane.showConfirmDialog(rootPane,"Deseja Excluir");
        
        if(resposta==JOptionPane.YES_OPTION)
        {
        mode.setCodigo(Integer.parseInt(jTextCodigo.getText()));
        control.Excluir(mode);
        jTextFieldNomeMoradorCont.setEnabled(false);
        jTextFieldNumeroCasa1.setEnabled(false);
        jTextFieldContaApagar.setEnabled(false);
        jTextFieldContasPagas.setEnabled(false);
        
        
        
        }
       preencherTabela("select * from contas order by nome_morador");
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableMoradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMoradorMouseClicked
      //mouse
        //clickted
        //alterar travez de mouse
        String nome_morador=""+jTableMorador.getValueAt(jTableMorador.getSelectedRow(),1);
        conex.conexao();
        conex.executaSql("select * from contas where nome_morador='"+nome_morador+"'");
         try {
            conex.rs.first();
           jTextCodigo.setText(String.valueOf(conex.rs.getInt("cod_contas")));
           jTextFieldNomeMoradorCont.setText(conex.rs.getString("nome_morador"));
           jTextFieldNumeroCasa1.setText(conex.rs.getString("numero_casa"));
           jTextFieldContaApagar.setText(conex.rs.getString("contas_apagar"));
           jTextFieldContasPagas.setText(conex.rs.getString("contas_pagas"));
           
           
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao selecionar dados"+ex);
        }
         jTextFieldNomeMoradorCont.setEnabled(false);
         jTextFieldNumeroCasa1.setEnabled(false);
         jTextFieldContaApagar.setEnabled(false);
         jTextFieldContasPagas.setEnabled(false);
         
        jButtonEditar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonExcluir.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonLimpar.setEnabled(false);
    }//GEN-LAST:event_jTableMoradorMouseClicked

    public void preencherTabela(String Sql)
    {
    ArrayList dados=new ArrayList();
    
    String [] colunas=new String[]{"ID","Nome Morador","Número da casa","Contas Apagar","contas Pagas"};
    
    conex.conexao();
    conex.executaSql(Sql);
    
    try{
    
    conex.rs.first();
    
    do {
    
    dados.add(new Object[]{conex.rs.getInt("cod_contas"),conex.rs.getString("nome_morador"),conex.rs.getString("numero_casa"),conex.rs.getString("contas_apagar"),conex.rs.getString("contas_pagas")});
       
    
       }while(conex.rs.next());
    
    }catch(SQLException ex)
       {
        JOptionPane.showMessageDialog(rootPane,"Erro ao preencher ArrayLyst"+ex);
       }
        ModeloTabelaContas modelo=new ModeloTabelaContas(dados,colunas);
        
        jTableMorador.setModel(modelo);
        
         jTableMorador.getColumnModel().getColumn(0).setPreferredWidth(28);
         jTableMorador.getColumnModel().getColumn(0).setResizable(false);
         
         jTableMorador.getColumnModel().getColumn(1).setPreferredWidth(203);
         jTableMorador.getColumnModel().getColumn(1).setResizable(false);
         
         jTableMorador.getColumnModel().getColumn(2).setPreferredWidth(103);
         jTableMorador.getColumnModel().getColumn(2).setResizable(false);
         
         jTableMorador.getColumnModel().getColumn(3).setPreferredWidth(123);
         jTableMorador.getColumnModel().getColumn(3).setResizable(false);
         
        jTableMorador.getColumnModel().getColumn(4).setPreferredWidth(133);
         jTableMorador.getColumnModel().getColumn(4).setResizable(false);
       
        
        
        jTableMorador.setAutoResizeMode(jTableMorador.AUTO_RESIZE_OFF);
        jTableMorador.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTableMorador.getTableHeader().setReorderingAllowed(false);
        
        
        
    conex.Desconectar();
    }
    
    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisas;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableMorador;
    private javax.swing.JTextField jTextCodigo;
    private javax.swing.JTextField jTextFieldContaApagar;
    private javax.swing.JTextField jTextFieldContasPagas;
    private javax.swing.JTextField jTextFieldNomeMoradorCont;
    private javax.swing.JTextField jTextFieldNumeroCasa1;
    private javax.swing.JTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables
}
