/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConection.ConexaoBD;
import modeloDao.DaoDevedor;
import modeloBeans.BeansDevedor;
import modeloBeans.ModeloTabelaDevedor;


public class ControleDeDevedore extends javax.swing.JFrame {
    
    BeansDevedor mod=new BeansDevedor();
    DaoDevedor contro=new DaoDevedor();
    ConexaoBD conex=new ConexaoBD();
    int flag=0;
    
    
    
    public ControleDeDevedore() {
        initComponents();
        
        
        preencherTabela("select*from moradores_inadimplentes order by nome_devedor");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValorDivida = new javax.swing.JTextField();
        jTextFieldCodContas = new javax.swing.JTextField();
        jTextFieldDevedores = new javax.swing.JTextField();
        jButtonSalva = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonEdita = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDevedor = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jTextFieldPesquisaDevedores = new javax.swing.JTextField();
        jButtonCancelar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAnoDivida1 = new javax.swing.JTextField();
        jTextFieldAnoDivida2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonEdita1 = new javax.swing.JButton();
        jButtonEdita2 = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setText("Controle De Devedores:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 220, 53);

        jLabel2.setText("NOME DO DEVEDOR:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 130, 21);

        jLabel3.setText("VALOR DA DIVIDA:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 190, 108, 16);

        jLabel4.setText("ANO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 250, 30, 16);

        jTextFieldValorDivida.setEnabled(false);
        jTextFieldValorDivida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorDividaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValorDivida);
        jTextFieldValorDivida.setBounds(200, 182, 126, 30);

        jTextFieldCodContas.setEnabled(false);
        getContentPane().add(jTextFieldCodContas);
        jTextFieldCodContas.setBounds(90, 70, 80, 22);

        jTextFieldDevedores.setEnabled(false);
        jTextFieldDevedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDevedoresActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDevedores);
        jTextFieldDevedores.setBounds(200, 122, 126, 30);

        jButtonSalva.setText("SALVAR:");
        jButtonSalva.setEnabled(false);
        jButtonSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalva);
        jButtonSalva.setBounds(140, 420, 90, 25);

        jButtonNovo.setText("Novo:");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(30, 420, 90, 25);

        jButtonEdita.setText("EDITAR:");
        jButtonEdita.setEnabled(false);
        jButtonEdita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdita);
        jButtonEdita.setBounds(460, 420, 90, 25);

        jButtonLimpar.setText("Limpar:");
        jButtonLimpar.setEnabled(false);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(250, 420, 90, 25);

        jTableDevedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDevedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDevedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDevedor);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 60, 370, 340);

        jButton5.setText("PESQUISAR:");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(640, 20, 110, 30);

        jTextFieldPesquisaDevedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaDevedoresActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisaDevedores);
        jTextFieldPesquisaDevedores.setBounds(380, 20, 240, 30);

        jButtonCancelar1.setText("Cancelar:");
        jButtonCancelar1.setEnabled(false);
        jButtonCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar1);
        jButtonCancelar1.setBounds(350, 420, 90, 25);

        jLabel5.setText("ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 70, 17, 16);

        jTextFieldAnoDivida1.setEnabled(false);
        jTextFieldAnoDivida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnoDivida1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAnoDivida1);
        jTextFieldAnoDivida1.setBounds(200, 242, 126, 30);

        jTextFieldAnoDivida2.setEnabled(false);
        getContentPane().add(jTextFieldAnoDivida2);
        jTextFieldAnoDivida2.setBounds(200, 250, 126, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 50, 770, 2);

        jButtonEdita1.setText("EDITAR:");
        jButtonEdita1.setEnabled(false);
        jButtonEdita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdita1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdita1);
        jButtonEdita1.setBounds(460, 420, 90, 25);

        jButtonEdita2.setText("EDITAR:");
        jButtonEdita2.setEnabled(false);
        jButtonEdita2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdita2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEdita2);
        jButtonEdita2.setBounds(460, 420, 90, 25);

        jButtonExcluir.setText("Excluir:");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir);
        jButtonExcluir.setBounds(580, 420, 75, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/fundo de imagem.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -4, 780, 490);

        setSize(new java.awt.Dimension(793, 533));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaActionPerformed

       if(flag==1){ 
        
        jTextFieldDevedores.setEnabled(false);
        jTextFieldAnoDivida1.setEnabled(false);
        jTextFieldValorDivida.setEditable(false);
        
        
        
        mod.setNome(jTextFieldDevedores.getText());
        mod.setAno(jTextFieldCodContas.getText());
        mod.setValor(jTextFieldValorDivida.getText());
        
        contro.salvar0(mod);
       
        jTextFieldAnoDivida1.setText("");
        jTextFieldDevedores.setText("");
        jTextFieldValorDivida.setText("");
        
        jButtonLimpar.setEnabled(false);
        jButtonSalva.setEnabled(false);
        jButtonCancelar1.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEdita.setEnabled(false);
        
       //comecei errado
        preencherTabela("select*from moradores_inadimplentes order by nome_devedor");
       }else{
       
       mod.setCodigo(Integer.parseInt(jTextFieldCodContas.getText()));
       mod.setNome(jTextFieldDevedores.getText());
       
       mod.setValor(jTextFieldValorDivida.getText());
       
       mod.setAno(jTextFieldAnoDivida1.getText());
       
       contro.Editar(mod);
       
        jTextFieldDevedores.setEnabled(false);
        jTextFieldAnoDivida1.setEnabled(false);
        jTextFieldValorDivida.setEditable(false);
        jTextFieldValorDivida.setEnabled(false);
       
        jTextFieldAnoDivida1.setText("");
        jTextFieldDevedores.setText("");
        jTextFieldValorDivida.setText("");
        jTextFieldDevedores.setText("");
        
        jButtonLimpar.setEnabled(false);
        jButtonSalva.setEnabled(false);
        jButtonCancelar1.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonEdita.setEnabled(false);
        
        preencherTabela("select*from moradores_inadimplentes order by nome_devedor");
       }
       
       
    }//GEN-LAST:event_jButtonSalvaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        mod.setPesquisar(jTextFieldPesquisaDevedores.getText());
        BeansDevedor model=contro.buscarDevdor(mod);
        
        
        jTextFieldDevedores.setText(model.getNome());
        jTextFieldValorDivida.setText(model.getValor());
        jTextFieldAnoDivida1.setText(model.getAno());
        jTextFieldCodContas.setText(String.valueOf(mod.getCodigo()));
        
       
        jButtonEdita.setEnabled(true);
        jButtonCancelar1.setEnabled(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldPesquisaDevedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaDevedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisaDevedoresActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        
        flag=1;
        
        jTextFieldAnoDivida1.setEnabled(true);
        jTextFieldDevedores.setEnabled(true);
        jTextFieldValorDivida.setEnabled(true);
        
        
        jButtonLimpar.setEnabled(true);
        jButtonSalva.setEnabled(true);
        jButtonCancelar1.setEnabled(true);
        
         jTextFieldCodContas.setText("");
        jTextFieldDevedores.setText("");
        jTextFieldValorDivida.setText("");
        jTextFieldCodContas.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        
        jTextFieldCodContas.setText("");
        jTextFieldDevedores.setText("");
        jTextFieldValorDivida.setText("");
        
        jButtonLimpar.setEnabled(false);
        jButtonSalva.setEnabled(false);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonEditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaActionPerformed
        
         flag=2;
         
        
        jTextFieldDevedores.setEnabled(true);
        jTextFieldValorDivida.setEnabled(true);
        jTextFieldAnoDivida1.setEnabled(true);
        
        
        jButtonNovo.setEnabled(false);
        jButtonEdita.setEnabled(false);
        jButtonLimpar.setEnabled(false);
        jButtonSalva.setEnabled(true);
        jButtonCancelar1.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonLimpar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonEditaActionPerformed

    private void jButtonCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelar1ActionPerformed
        
        
        jTextFieldDevedores.setText("");
        jTextFieldValorDivida.setText("");
        jTextFieldAnoDivida1.setText("");
        
        jTextFieldDevedores.setEnabled(!true);
        jTextFieldAnoDivida1.setEnabled(!true);
        jTextFieldValorDivida.setEnabled(!true);
        
        
        
        jButtonEdita.setEnabled(!true);
        jButtonLimpar.setEnabled(!true);
        jButtonSalva.setEnabled(!true);
        jButtonCancelar1.setEnabled(!true);
        jButtonNovo.setEnabled(true);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelar1ActionPerformed

    private void jButtonEdita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdita1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEdita1ActionPerformed

    private void jButtonEdita2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdita2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEdita2ActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
     int  resposta=0;
     resposta=JOptionPane.showConfirmDialog(rootPane,"Deseja Excluir");
        
        
        if(resposta==JOptionPane.YES_OPTION)
        {
        mod.setCodigo(Integer.parseInt(jTextFieldCodContas.getText()));
        contro.Excluir(mod);
        
        jTextFieldDevedores.setEnabled(false);
        jTextFieldAnoDivida1.setEnabled(false);
        jTextFieldValorDivida.setEditable(false);
        jTextFieldValorDivida.setEnabled(false); 
        
        
       
        }
         preencherTabela("select*from moradores_inadimplentes order by nome_devedor");
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTableDevedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDevedorMouseClicked
        //mouse cliketd
        //eduardo
        //
        String nome_morador=""+jTableDevedor.getValueAt(jTableDevedor.getSelectedRow(),2);
        conex.conexao();
        conex.executaSql("select * from moradores_inadimplentes where divida ='"+nome_morador+"'");
        
          try {
            conex.rs.first();
            
           jTextFieldCodContas.setText(String.valueOf(conex.rs.getInt("cod_devedor")));
           jTextFieldDevedores.setText(conex.rs.getString("nome_devedor"));
           jTextFieldValorDivida.setText(conex.rs.getString("divida"));
           jTextFieldAnoDivida1.setText(conex.rs.getString("ano_divida"));
           
    }                                       
     catch (SQLException ex)
     {
        JOptionPane.showMessageDialog(null,"Erro ao selecionar dados"+ex);          
     }
             jButtonNovo.setEnabled(false);
             jButtonEdita.setEnabled(true);
             jButtonExcluir.setEnabled(true);
             jButtonCancelar1.setEnabled(true);
             
             jTextFieldDevedores.setEnabled(false);
             jTextFieldAnoDivida1.setEnabled(false);
             jTextFieldValorDivida.setEditable(false);
             jTextFieldValorDivida.setEnabled(false); 
    }//GEN-LAST:event_jTableDevedorMouseClicked

    private void jTextFieldValorDividaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorDividaActionPerformed
        // TiiiiODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorDividaActionPerformed

    private void jTextFieldAnoDivida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnoDivida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnoDivida1ActionPerformed

    private void jTextFieldDevedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDevedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDevedoresActionPerformed

    
    public void preencherTabela(String Sql)
    {
    ArrayList dados=new ArrayList();
    
    String [] colunas=new String[]{"ID","Nome","Valor Da Divida","Ano Divida"};
    
    conex.conexao();
    conex.executaSql(Sql);
    
    try{
    
    conex.rs.first();
    
    do {
    
    dados.add(new Object[]{conex.rs.getInt("cod_devedor"),conex.rs.getString("nome_devedor"),conex.rs.getString("divida"),conex.rs.getString("ano_divida")});
       
    
       }while(conex.rs.next());
    
    }catch(SQLException ex)
       {
        JOptionPane.showMessageDialog(rootPane,"Erro ao preencher ArrayLyst"+ex);
       }
        ModeloTabelaDevedor modelo=new ModeloTabelaDevedor(dados,colunas);
        
        jTableDevedor.setModel(modelo);
        
        jTableDevedor.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTableDevedor.getColumnModel().getColumn(0).setResizable(false);
        
        jTableDevedor.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableDevedor.getColumnModel().getColumn(1).setResizable(false);
        
        jTableDevedor.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableDevedor.getColumnModel().getColumn(2).setResizable(false);
        
        jTableDevedor.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableDevedor.getColumnModel().getColumn(3).setResizable(false);
       
        
        
        jTableDevedor.getTableHeader().setReorderingAllowed(false);
        jTableDevedor.setAutoResizeMode(jTableDevedor.AUTO_RESIZE_OFF);
        jTableDevedor.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
    conex.Desconectar();
    }
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleDeDevedore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleDeDevedore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleDeDevedore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleDeDevedore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleDeDevedore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCancelar1;
    private javax.swing.JButton jButtonEdita;
    private javax.swing.JButton jButtonEdita1;
    private javax.swing.JButton jButtonEdita2;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDevedor;
    private javax.swing.JTextField jTextFieldAnoDivida1;
    private javax.swing.JTextField jTextFieldAnoDivida2;
    private javax.swing.JTextField jTextFieldCodContas;
    private javax.swing.JTextField jTextFieldDevedores;
    private javax.swing.JTextField jTextFieldPesquisaDevedores;
    private javax.swing.JTextField jTextFieldValorDivida;
    // End of variables declaration//GEN-END:variables

    private void salvar3(BeansDevedor mode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void salvar4(BeansDevedor mode) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
